### ISSUE TITLE
Composer requirements

### ISSUE THREAD

**Issue by MrGekko** [ffuenf/Ffuenf_Pagespeed#1]
Hi could you please remove the composer requirements.
Because i rely on the composer installer 3 and that does not work anymore.
"aoepeople/composer-installers": "*",
"colinmollenhour/modman": "*"

**Comment by arosenhagen** [comment]
so you would propose a dependency to https://github.com/Cotya/magento-composer-installer ?

**Comment by MrGekko** [comment]
No :) no dependency would be great. Because people can chose the installer they want in root composer.json.

**Comment by MrGekko** [comment]
BTW. when I put:
  "replace": {
    "aoepeople/composer-installers": "*"
  },
into my root composer.json everything works fine.
